export enum SignalType {
    NEW_CHAT = "NEW_CHAT",
    TYPING = "TYPING",
    NEW_UNREAD_COUNT = "NEW_UNREAD_COUNT",
    NEW_MESSAGE = "NEW_MESSAGE",
    READ = "READ",
    ONLINE_STATUSES = "ONLINE_STATUSES",
}
